# Generated by Django 3.2.9 on 2021-12-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twostep',
            field=models.BooleanField(default=True),
        ),
    ]
