# Generated by Django 3.2.9 on 2021-12-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_user_twostep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twostep',
            new_name='nottwostep',
        ),
    ]
