# Generated by Django 3.2.9 on 2021-12-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_rename_twostep_user_nottwostep'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login2stepverify',
            field=models.BooleanField(default=True),
        ),
    ]
