# Generated by Django 3.2.9 on 2021-12-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_user_login2stepverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('--', '--'), ('SELLER', 'SELLER'), ('BUYER', 'BUYER')], default='--', max_length=255),
        ),
    ]
