# Generated by Django 3.2.9 on 2021-12-18 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=products.models.upload_path_handler)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Exotic vegetable', 'Exotic vegetable'), ('Meat/Seafood', 'Meat/Seafood'), ('Daily essentials', 'Daily essentials'), ('Dairy Products', 'Dairy Products'), ('Healthy Food', 'Healthy Food'), ('fruits', 'fruits'), ('Indian Grocery', 'Indian Grocery'), ('Bakery Items', 'Bakery Items')], default='', max_length=255)),
                ('min_quantity', models.IntegerField()),
                ('below_min_dis', models.CharField(max_length=5)),
                ('total_stock', models.IntegerField()),
                ('above_min_dis', models.CharField(max_length=5)),
                ('units', models.CharField(choices=[('kilogram', 'kg'), ('gram', 'g'), ('litre', 'l'), ('milli-litre', 'ml'), ('unit', 'unit')], default='kilogram', max_length=255)),
                ('countInStock', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=255)),
                ('pinCode', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
