# Generated by Django 3.2.9 on 2021-12-19 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20211219_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCartItem', models.IntegerField(default=0)),
                ('totalCartItemFromSameManufacturer', models.IntegerField(default=0)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200)),
                ('taxPrice', models.DecimalField(decimal_places=2, default=18, max_digits=7)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='min_quantity',
            new_name='min_order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='products_ordered',
        ),
        migrations.RemoveField(
            model_name='product',
            name='above_min_dis',
        ),
        migrations.RemoveField(
            model_name='product',
            name='below_min_dis',
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Exotic vegetable', 'Exotic vegetable'), ('Meat/Seafood', 'Meat/Seafood'), ('Daily essentials', 'Daily essentials'), ('Dairy Products', 'Dairy Products'), ('Healthy Food', 'Healthy Food'), ('fruits', 'fruits'), ('Indian Grocery', 'Indian Grocery'), ('Bakery Items', 'Bakery Items')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('unit', 'unit')], max_length=255),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('wholesale_price', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cart')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
