# Generated by Django 3.2.9 on 2021-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211219_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
