# Generated by Django 3.2.9 on 2021-12-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_wholesale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published',
        ),
        migrations.AddField(
            model_name='product',
            name='static_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cart',
            name='manufacturer_name',
            field=models.CharField(blank=True, default='A', max_length=200),
        ),
    ]
