# Generated by Django 3.2.9 on 2021-12-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211220_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='static_stock',
        ),
    ]
