# Generated by Django 3.2.9 on 2021-12-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_static_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
